=== Lehapuz/bosovec/XMLParcer/target/classes/banks.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="https://www.example.com/Banks" elementFormDefault="qualified">
    <xs:element name="banks">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="bank" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="name" type="xs:string">
                            </xs:element>
                            <xs:element name="country" type="xs:string">
                            </xs:element>
                            <xs:element name="town" type="xs:string">
                            </xs:element>
                            <xs:element name="typeContribution" type="xs:simpleType" maxOccurs="5">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:enumeration value="toDemand">
                                        </xs:enumeration>
                                        <xs:enumeration value="urgent">
                                        </xs:enumeration>
                                        <xs:enumeration value="estimated">
                                        </xs:enumeration>
                                        <xs:enumeration value="accumulative">
                                        </xs:enumeration>
                                        <xs:enumeration value="savings">
                                        </xs:enumeration>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="depositor" minOccurs="0" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="id" type="xs:positiveInteger">
                                        </xs:element>
                                        <xs:element name="amountOnDeposit">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:positiveInteger">
                                                    <xs:minInclusive value="1000">
                                                    </xs:minInclusive>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="profitability" type="xs:decimal">
                                        </xs:element>
                                        <xs:element name="timeConstraints" type="xs:dateTime">
                                        </xs:element>
                                        <xs:element name="typeContribution" type="xs:element">
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Lehapuz/bosovec/XMLParser/src/main/resources/banks.xml
<?xml version="1.0" encoding="UTF-8"?>
<banks xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:noNamespaceSchemaLocation="banks.xsd" >
    <bank>
        <name>DeutscheBank</name>
        <country>Germany</country>
        <town>Berlin</town>
        <typeContribution>toDemand</typeContribution>
        <typeContribution>urgent</typeContribution>
        <typeContribution>estimated</typeContribution>
        <typeContribution>accumulative</typeContribution>
        <typeContribution>savings</typeContribution>
        <depositor>
            <id>1</id>
            <amountOnDeposit>100000</amountOnDeposit>
            <profitability>0.3</profitability>
            <timeConstraints>2022-03-14T00:00:00</timeConstraints>
            <typeContribution>urgent</typeContribution>
        </depositor>
        <depositor>
            <id>2</id>
            <amountOnDeposit>200000</amountOnDeposit>
            <profitability>0.25</profitability>
            <timeConstraints>2025-03-14T00:00:00</timeConstraints>
            <typeContribution>accumulative</typeContribution>
        </depositor>
        <depositor>
            <id>3</id>
            <amountOnDeposit>2000000</amountOnDeposit>
            <profitability>0.4</profitability>
            <timeConstraints>2025-05-14T00:00:00</timeConstraints>
            <typeContribution>toDemand</typeContribution>
        </depositor>
        <depositor>
            <id>4</id>
            <amountOnDeposit>5000000</amountOnDeposit>
            <profitability>0.45</profitability>
            <timeConstraints>2025-03-14T00:00:00</timeConstraints>
            <typeContribution>accumulative</typeContribution>
        </depositor>
    </bank>
    <bank>
        <name>CommercBank</name>
        <country>Germany</country>
        <town>Hamburg</town>
        <typeContribution>urgent</typeContribution>
        <typeContribution>estimated</typeContribution>
        <typeContribution>accumulative</typeContribution>
        <typeContribution>savings</typeContribution>
        <depositor>
            <id>5</id>
            <amountOnDeposit>1000000</amountOnDeposit>
            <profitability>0.35</profitability>
            <timeConstraints>2025-04-15T00:00:00</timeConstraints>
            <typeContribution>urgent</typeContribution>
        </depositor>
        <depositor>
            <id>6</id>
            <amountOnDeposit>1200000</amountOnDeposit>
            <profitability>0.33</profitability>
            <timeConstraints>2026-10-25T00:00:00</timeConstraints>
            <typeContribution>savings</typeContribution>
        </depositor>
        <depositor>
            <id>7</id>
            <amountOnDeposit>22000000</amountOnDeposit>
            <profitability>0.4</profitability>
            <timeConstraints>2028-06-12T00:00:00</timeConstraints>
            <typeContribution>estimated</typeContribution>
        </depositor>
        <depositor>
            <id>8</id>
            <amountOnDeposit>5100000</amountOnDeposit>
            <profitability>0.28</profitability>
            <timeConstraints>2029-10-30T00:00:00</timeConstraints>
            <typeContribution>accumulative</typeContribution>
        </depositor>
    </bank>
    <bank>
        <name>BundesBank</name>
        <country>Germany</country>
        <town>Hannover</town>
        <typeContribution>urgent</typeContribution>
        <typeContribution>estimated</typeContribution>
        <typeContribution>accumulative</typeContribution>
        <depositor>
            <id>9</id>
            <amountOnDeposit>1500000</amountOnDeposit>
            <profitability>0.36</profitability>
            <timeConstraints>2024-06-18T00:00:00</timeConstraints>
            <typeContribution>urgent</typeContribution>
        </depositor>
        <depositor>
            <id>10</id>
            <amountOnDeposit>1600000</amountOnDeposit>
            <profitability>0.35</profitability>
            <timeConstraints>2027-11-26T00:00:00</timeConstraints>
            <typeContribution>accumulative</typeContribution>
        </depositor>
        <depositor>
            <id>11</id>
            <amountOnDeposit>2000000</amountOnDeposit>
            <profitability>0.4</profitability>
            <timeConstraints>2029-11-08T00:00:00</timeConstraints>
            <typeContribution>estimated</typeContribution>
        </depositor>
        <depositor>
            <id>12</id>
            <amountOnDeposit>6100000</amountOnDeposit>
            <profitability>0.4</profitability>
            <timeConstraints>2027-05-25T00:00:00</timeConstraints>
            <typeContribution>accumulative</typeContribution>
        </depositor>
    </bank>
</banks>
